### ISSUE TITLE
Manager Page

### ISSUE THREAD

**Issue by plmwd** [ChrisFischer-MTA/COP4331_Project-1#12]
# TODO

## Cosmetics:
- [x]  Initial look when the page is first loaded
- [x]  Visually select 
- [x]  Show selected contact information (readonly)
- [x]  Show editable fields (when in edit state)
- [x]  Alerts for errors
- [ ]  Save confirmation popups

## Frontend Logic:
- [x]  NOSEL manager state when the page is first loaded
- [x]  VIEW state for readonly contact viewing
- [x]  EDIT state for editing a selected contact

## REST API calls (too lazy right now to go lookup the actual endpoint name):
- [x]  search
- [x]  update contact information REST API call
- [x]  read contact information REST API call
- [x]  delete contact REST API call

**Comment by plmwd** [comment]
API integration done, but not well tested. Will open up bug issues if needed.
